
name: Terraform CI CD Pipeline for Deleting AWS Resources
run-name: ${{ github.actor }} has triggered the pipeline

on:
  push:
    branches:
      - 'main'

env:
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-infra:
    name: terraform-ci-cd-cleaner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # Update to the latest version supporting Node.js 20
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 # Update to the latest version if available
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: ./Terraform-VPC
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          TF_LOG: DEBUG
